Repository webonyx/graphql-php, pull requests merged in 2021-01, with the labels that each got.

#763 Simplify type hints in wrapping types
  src/Type/Definition/ListOfType.php
  src/Type/Definition/NonNull.php
Labels: bug

#761 Add comprehensive test for the default resolver
  tests/Executor/ExecutorTest.php
Labels: enhancement

#766 Do not add errors key when empty
  src/Executor/ExecutionResult.php
  tests/Executor/ExecutionResultTest.php
Labels: bug

#749 Update link to Laravel PSR7 handling to current version in docs
  docs/executing-queries.md
Labels: docs

#756 fix query plan for wrapped types
  src/Type/Definition/QueryPlan.php
  tests/Type/QueryPlanTest.php
Labels: bug

#767 Allow pushing nodes to NodeList via []=
  CHANGELOG.md
  src/Language/AST/NodeList.php
  tests/Language/NodeListTest.php
Labels: bug

#740 Implement support for interfaces implementing interfaces
  phpstan-baseline.neon
  src/Executor/ReferenceExecutor.php
  src/Experimental/Executor/Collector.php
  src/Experimental/Executor/CoroutineExecutor.php
  src/Language/AST/InterfaceTypeDefinitionNode.php
  src/Language/AST/InterfaceTypeExtensionNode.php
  src/Language/Parser.php
  src/Language/Printer.php
  src/Language/Visitor.php
  src/Type/Definition/ImplementingType.php
  src/Type/Definition/InterfaceType.php
  src/Type/Definition/ObjectType.php
  src/Type/Introspection.php
  src/Type/Schema.php
  src/Type/SchemaValidationContext.php
  src/Utils/ASTDefinitionBuilder.php
  src/Utils/BreakingChangesFinder.php
  src/Utils/BuildClientSchema.php
  src/Utils/InterfaceImplementations.php
  src/Utils/SchemaExtender.php
  src/Utils/SchemaPrinter.php
  src/Utils/TypeComparators.php
  src/Utils/TypeInfo.php
  src/Validator/Rules/PossibleFragmentSpreads.php
  tests/Executor/TestClasses/Cat.php
  tests/Executor/TestClasses/Dog.php
  tests/Executor/UnionInterfaceTest.php
  tests/Language/SchemaParserTest.php
  tests/Language/SchemaPrinterTest.php
  tests/Language/schema-kitchen-sink.graphql
  tests/Type/DefinitionTest.php
  tests/Type/IntrospectionTest.php
  tests/Type/LazyTypeLoaderTest.php
  tests/Type/TypeLoaderTest.php
  tests/Type/ValidationTest.php
  tests/Utils/BreakingChangesFinderTest.php
  tests/Utils/BuildClientSchemaTest.php
  tests/Utils/BuildSchemaTest.php
  tests/Utils/SchemaExtenderTest.php
  tests/Utils/SchemaPrinterTest.php
  tests/Validator/FragmentsOnCompositeTypesTest.php
Labels: enhancement

#751 Reify AST node types and remove unneeded nullability
  phpstan-baseline.neon
  src/Language/AST/EnumTypeDefinitionNode.php
  src/Language/AST/EnumTypeExtensionNode.php
  src/Language/AST/FieldNode.php
  src/Language/AST/InlineFragmentNode.php
  src/Language/AST/InputObjectTypeDefinitionNode.php
  src/Language/AST/InputObjectTypeExtensionNode.php
  src/Language/AST/InterfaceTypeDefinitionNode.php
  src/Language/AST/InterfaceTypeExtensionNode.php
  src/Language/AST/Location.php
  src/Language/AST/ObjectTypeDefinitionNode.php
  src/Language/AST/ScalarTypeExtensionNode.php
  src/Language/AST/SchemaTypeExtensionNode.php
  src/Language/AST/StringValueNode.php
  src/Language/AST/UnionTypeDefinitionNode.php
  src/Language/AST/UnionTypeExtensionNode.php
  src/Language/Parser.php
  src/Type/Schema.php
  src/Utils/ASTDefinitionBuilder.php
  src/Utils/BuildSchema.php
  src/Utils/SchemaExtender.php
  tests/Type/ValidationTest.php
  tests/Utils/SchemaExtenderTest.php
Labels: bug
