Repository webonyx/graphql-php, pull requests merged in 2021-08, with the labels that each got.

#898 Move debugMessage and trace into error extensions
  CHANGELOG.md
  docs/error-handling.md
  src/Error/FormattedError.php
  tests/Executor/AbstractPromiseTest.php
  tests/Executor/AbstractTest.php
  tests/Executor/ListsTest.php
  tests/Executor/MutationsTest.php
  tests/Executor/NonNullTest.php
  tests/Server/QueryExecutionTest.php
  tests/Type/EnumTypeTest.php
Labels: BC break, enhancement

#491 Warn about orphaned object types
  src/Executor/ReferenceExecutor.php
  tests/Executor/AbstractTest.php
Labels: enhancement

#916 Always throw `RequestError` with useful message when clients provide an invalid JSON body
  CHANGELOG.md
  src/Server/Helper.php
  tests/Server/RequestParsingTest.php
Labels: bug
