Repository webonyx/graphql-php, pull requests merged in 2021-05, with the labels that each got.

#860 Improve performance of subtype checks
  benchmarks/StarWarsBench.php
  benchmarks/shim.php
  src/Type/Schema.php
  tests/Type/LazyTypeLoaderTest.php
  tests/Type/SchemaTest.php
  tests/Type/TypeLoaderTest.php
Labels: enhancement

#862 Improve performance of subtype checks (v14 backport)
  benchmarks/StarWarsBench.php
  benchmarks/shim.php
  src/Type/Schema.php
  tests/Type/LazyTypeLoaderTest.php
  tests/Type/SchemaTest.php
  tests/Type/TypeLoaderTest.php
Labels: enhancement

#861 Lazy field definitions
  benchmarks/Utils/QueryGenerator.php
  phpstan-baseline.neon
  src/Executor/ReferenceExecutor.php
  src/Type/Definition/FieldDefinition.php
  src/Type/Definition/HasFieldsType.php
  src/Type/Definition/InterfaceType.php
  src/Type/Definition/ObjectType.php
  src/Type/Definition/TypeWithFields.php
  src/Type/Definition/UnresolvedFieldDefinition.php
  src/Type/SchemaValidationContext.php
  src/Utils/TypeInfo.php
  src/Validator/Rules/FieldsOnCorrectType.php
  src/Validator/Rules/OverlappingFieldsCanBeMerged.php
  src/Validator/Rules/QuerySecurityRule.php
  tests/Type/DefinitionTest.php
Labels: backport-to-v14, enhancement

#868 Update examples/02-shorthand
  examples/02-schema-definition-language/README.md
  examples/02-schema-definition-language/graphql.php
  examples/02-shorthand/graphql.php
  examples/02-shorthand/rootvalue.php
  examples/02-shorthand/schema.graphqls
  phpcs.xml.dist
  phpstan.neon.dist
Labels: docs

#870 Update standard server example
  examples/00-hello-world/README.md
  examples/00-hello-world/graphql.php
  examples/02-schema-definition-language/README.md
  examples/03-standard-server/README.md
  examples/03-standard-server/graphql.php
  phpcs.xml.dist
  phpstan.neon.dist
Labels: docs
