Repository webonyx/graphql-php, pull requests merged in 2021-04, with the labels that each got.

#818 Restructure docs
  .gitattributes
  CHANGELOG.md
  CONTRIBUTING.md
  UPGRADE.md
  composer.json
  docs/about.md
  docs/best-practices.md
  docs/class-reference.md
  docs/concepts.md
  docs/data-fetching.md
  docs/error-handling.md
  docs/executing-queries.md
  docs/getting-started.md
  docs/how-it-works.md
  docs/schema-definition-language.md
  docs/schema-definition.md
  docs/type-definitions/directives.md
  docs/type-definitions/enums.md
  docs/type-definitions/inputs.md
  docs/type-definitions/interfaces.md
  docs/type-definitions/introduction.md
  docs/type-definitions/lists-and-nonnulls.md
  docs/type-definitions/object-types.md
  docs/type-definitions/scalar-types.md
  docs/type-definitions/unions.md
  docs/type-system/index.md
  examples/00-hello-world/graphql.php
  examples/03-server/README.md
  examples/03-server/graphql.php
  generate-class-reference.php
  mkdocs.yml
  src/Executor/ReferenceExecutor.php
  src/Experimental/Executor/CoroutineExecutor.php
  src/Language/Parser.php
  src/Language/Visitor.php
  src/Server/StandardServer.php
  src/Type/Schema.php
  src/Type/SchemaConfig.php
  src/Utils/BuildSchema.php
  src/Utils/SchemaPrinter.php
  src/Utils/TypeInfo.php
  src/Validator/DocumentValidator.php
  tests/Executor/AbstractTest.php
  tests/Executor/ExecutorLazySchemaTest.php
  tests/Type/DefinitionTest.php
Labels: docs

#829 Fix style for examples/00-hello-world
  examples/00-hello-world/graphql.php
  phpcs.xml.dist
  phpstan.neon.dist
Labels: docs

#770 Ensure properties annotated to hold NodeList are not null
  CHANGELOG.md
  phpstan-baseline.neon
  src/Language/AST/InterfaceTypeExtensionNode.php
  src/Language/Printer.php
  src/Type/Definition/Directive.php
  src/Type/Definition/EnumType.php
  src/Type/Definition/FieldArgument.php
  src/Type/Definition/FieldDefinition.php
  src/Type/Definition/InputObjectType.php
  src/Type/Definition/InterfaceType.php
  src/Type/Definition/ObjectType.php
  src/Type/Definition/ScalarType.php
  src/Type/Definition/Type.php
  src/Type/Definition/UnionType.php
  src/Type/Introspection.php
  src/Type/Schema.php
  src/Type/SchemaConfig.php
  src/Type/SchemaValidationContext.php
  src/Utils/BreakingChangesFinder.php
  src/Utils/TypeInfo.php
  src/Utils/Utils.php
  src/Validator/Rules/KnownArgumentNamesOnDirectives.php
  src/Validator/Rules/OverlappingFieldsCanBeMerged.php
  src/Validator/Rules/ProvidedRequiredArguments.php
  src/Validator/Rules/ProvidedRequiredArgumentsOnDirectives.php
  src/Validator/Rules/QueryComplexity.php
  tests/Executor/ValuesTest.php
  tests/Type/ValidationTest.php
  tests/Utils/SchemaExtenderTest.php
Labels: bug

#844 Add navigation link to concept docs
  mkdocs.yml
Labels: docs

#847 Fix overly eager validation of repeatable directive usage
  CHANGELOG.md
  src/Type/SchemaValidationContext.php
  tests/Type/ValidationTest.php
Labels: backport-to-v14, bug

#848 Fix overly eager validation of repeatable directive usage
  CHANGELOG.md
  src/Type/SchemaValidationContext.php
  tests/Type/ValidationTest.php
Labels: bug

#854 Improve extendability of validator rules
  CHANGELOG.md
  src/Validator/Rules/CustomValidationRule.php
  src/Validator/Rules/DisableIntrospection.php
  src/Validator/Rules/ExecutableDefinitions.php
  src/Validator/Rules/FieldsOnCorrectType.php
  src/Validator/Rules/KnownArgumentNames.php
  src/Validator/Rules/KnownArgumentNamesOnDirectives.php
  src/Validator/Rules/KnownDirectives.php
  src/Validator/Rules/KnownFragmentNames.php
  src/Validator/Rules/KnownTypeNames.php
  src/Validator/Rules/LoneAnonymousOperation.php
  src/Validator/Rules/LoneSchemaDefinition.php
  src/Validator/Rules/NoFragmentCycles.php
  src/Validator/Rules/NoUndefinedVariables.php
  src/Validator/Rules/NoUnusedFragments.php
  src/Validator/Rules/NoUnusedVariables.php
  src/Validator/Rules/OverlappingFieldsCanBeMerged.php
  src/Validator/Rules/PossibleFragmentSpreads.php
  src/Validator/Rules/ProvidedRequiredArguments.php
  src/Validator/Rules/QueryComplexity.php
  src/Validator/Rules/QueryDepth.php
  src/Validator/Rules/QuerySecurityRule.php
  src/Validator/Rules/ScalarLeafs.php
  src/Validator/Rules/SingleFieldSubscription.php
  src/Validator/Rules/UniqueArgumentNames.php
  src/Validator/Rules/UniqueDirectivesPerLocation.php
  src/Validator/Rules/UniqueFragmentNames.php
  src/Validator/Rules/UniqueInputFieldNames.php
  src/Validator/Rules/UniqueOperationNames.php
  src/Validator/Rules/UniqueVariableNames.php
  src/Validator/Rules/ValidationRule.php
  src/Validator/Rules/ValuesOfCorrectType.php
  src/Validator/Rules/VariablesAreInputTypes.php
  src/Validator/Rules/VariablesInAllowedPosition.php
Labels: enhancement
