Repository webonyx/graphql-php, pull requests merged in 2021-03, with the labels that each got.

#470 Drop PHP 7.1 support
  .github/workflows/ci-build.yml
  CHANGELOG.md
  composer.json
Labels: BC break

#744 Drop PHP 7.2 support
  .github/workflows/ci-build.yml
  CHANGELOG.md
  composer.json
Labels: BC break

#746 Drop PHP 7.3 support
  .github/workflows/ci-build.yml
  CHANGELOG.md
  composer.json
Labels: BC break

#788 Update the debug flag name
  docs/executing-queries.md
Labels: docs

#806 Normalize composer.json
  .github/workflows/coding-standards.yml
  composer.json
Labels: enhancement

#778 Add typehints to SchemaPrinter
  src/Utils/SchemaPrinter.php
Labels: enhancement

#777 Clarify how NodeList accepts array's but returns Node's
  src/Language/AST/Node.php
  src/Language/AST/NodeList.php
  tests/Language/NodeListTest.php
Labels: enhancement

#786 Add fallback for directive.isRepeatable in BuildClientSchema
  src/Utils/BuildClientSchema.php
Labels: bug
