Repository webonyx/graphql-php, pull requests merged in 2021-07, with the labels that each got.

#876 Propagate error message for why leaf value serialization failed
  CHANGELOG.md
  src/Error/Error.php
  src/Executor/ReferenceExecutor.php
  src/Type/Definition/EnumType.php
  src/Utils/AST.php
  tests/Type/EnumTypeTest.php
Labels: enhancement

#889 Fix coercion of arbitrary objects to input objects
  CHANGELOG.md
  src/Utils/Value.php
  tests/Utils/CoerceValueTest.php
Labels: bug

#709 Base CHANGELOG.md on https://keepachangelog.com/en/1.0.0/
  CHANGELOG.md
Labels: docs

#808 Prettify markdown in GitHub action
  .github/workflows/format.yml
  docs/security.md
Labels: docs

#834 Fix "Only booleans are allowed" PHPStan errors
  phpstan-baseline.neon
  src/Language/Visitor.php
  src/Server/Helper.php
  src/Server/OperationParams.php
  src/Type/Definition/EnumType.php
  src/Type/Definition/QueryPlan.php
  src/Type/Definition/Type.php
  src/Type/Introspection.php
  src/Type/Schema.php
  src/Type/SchemaValidationContext.php
  src/Utils/AST.php
  src/Utils/ASTDefinitionBuilder.php
  src/Utils/PairSet.php
  src/Utils/SchemaExtender.php
  src/Utils/TypeInfo.php
  src/Utils/Utils.php
  src/Utils/Value.php
  src/Validator/Rules/FieldsOnCorrectType.php
  src/Validator/Rules/FragmentsOnCompositeTypes.php
  src/Validator/Rules/KnownDirectives.php
  src/Validator/Rules/KnownFragmentNames.php
  src/Validator/Rules/NoFragmentCycles.php
  src/Validator/Rules/OverlappingFieldsCanBeMerged.php
  src/Validator/Rules/PossibleFragmentSpreads.php
  src/Validator/Rules/ProvidedRequiredArguments.php
  src/Validator/Rules/ProvidedRequiredArgumentsOnDirectives.php
  src/Validator/Rules/QuerySecurityRule.php
  src/Validator/Rules/ScalarLeafs.php
  src/Validator/Rules/ValuesOfCorrectType.php
  src/Validator/Rules/VariablesAreInputTypes.php
  src/Validator/Rules/VariablesInAllowedPosition.php
  src/Validator/ValidationContext.php
  tests/Executor/DirectivesTest.php
  tests/Executor/LazyInterfaceTest.php
  tests/Executor/ValuesTest.php
  tests/Language/VisitorTest.php
  tests/Utils/AstFromValueTest.php
Labels: enhancement

#697 Fix namenode type / rewrite Printer
  CHANGELOG.md
  benchmarks/Utils/QueryGenerator.php
  phpstan-baseline.neon
  src/Executor/ReferenceExecutor.php
  src/Executor/Values.php
  src/Experimental/Executor/CoroutineExecutor.php
  src/Language/AST/FragmentDefinitionNode.php
  src/Language/AST/NodeList.php
  src/Language/Parser.php
  src/Language/Printer.php
  src/Type/Definition/QueryPlan.php
  src/Utils/SchemaExtender.php
  src/Validator/DocumentValidator.php
  src/Validator/Rules/OverlappingFieldsCanBeMerged.php
  tests/Language/PrinterTest.php
  tests/Language/SchemaPrinterTest.php
  tests/Language/SerializationTest.php
  tests/Language/VisitorTest.php
  tests/Utils/BuildSchemaTest.php
  tests/Utils/SchemaExtenderTest.php
Labels: enhancement

#830 Provide minimal spec-compliant error format
  UPGRADE.md
  composer.json
  docs/error-handling.md
  src/Error/ClientAware.php
  src/Error/Error.php
  src/Error/FormattedError.php
  src/Error/ProvidesExtensions.php
  src/Error/UserError.php
  src/Server/RequestError.php
  tests/Executor/AbstractTest.php
  tests/Executor/NonNullTest.php
  tests/Executor/VariablesTest.php
  tests/Server/QueryExecutionTest.php
  tests/Server/Unsafe.php
Labels: BC break, enhancement

#895 Handle `null` parent of list in `ValuesOfCorrectType::getVisitor`
  CHANGELOG.md
  src/Validator/Rules/ValuesOfCorrectType.php
  tests/UserArgsTest.php
Labels: bug

#822 Remove deprecated experimental CoroutineExecutor
  .github/workflows/ci.yml
  CHANGELOG.md
  phpstan-baseline.neon
  src/Experimental/Executor/Collector.php
  src/Experimental/Executor/CoroutineContext.php
  src/Experimental/Executor/CoroutineContextShared.php
  src/Experimental/Executor/CoroutineExecutor.php
  src/Experimental/Executor/Runtime.php
  src/Experimental/Executor/Strand.php
  src/GraphQL.php
  tests/Executor/DeferredFieldsTest.php
  tests/Experimental/Executor/CollectorTest.php
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitFieldThatHasArguments.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitFieldWithoutArguments.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitForInlineFragment.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitIfIncludeConditionTrue.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitIfSkipConditionFalse.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitIncludeAroundInlineFragment.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitIncludeFragmentSpread.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitIncludeSkipTF.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitObjectFieldForFragmentSpread.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitSingleInstrictionForSameResultName.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitSkipAroundInlineFragment.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitSkipFragmentSpread.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldEmitTypeName.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIfIncludeConditionFalse.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIfSkipConditionTrue.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIncludeAroundInlineFragment.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIncludeFragmentSpread.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIncludeSkipFF.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIncludeSkipFT.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitIncludeSkipTT.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitSkipAroundInlineFragment.json
  tests/Experimental/Executor/CollectorTestSnapshots/ShouldNotEmitSkipFragmentSpread.json
  tests/bootstrap.php
Labels: BC break

#712 Use `foreach` over slower functions `array_map()` and `Utils::map()`
  CHANGELOG.md
  benchmarks/BuildSchemaBench.php
  generate-class-reference.php
  src/Error/Error.php
  src/Error/FormattedError.php
  src/Error/ProvidesExtensions.php
  src/Executor/Promise/Adapter/ReactPromiseAdapter.php
  src/Executor/ReferenceExecutor.php
  src/Language/DirectiveLocation.php
  src/Language/Source.php
  src/Server/Helper.php
  src/Type/Definition/ObjectType.php
  src/Type/Schema.php
  src/Type/SchemaValidationContext.php
  src/Type/Validation/InputObjectCircularRefs.php
  src/Utils/AST.php
  src/Utils/ASTDefinitionBuilder.php
  src/Utils/BuildClientSchema.php
  src/Utils/BuildSchema.php
  src/Utils/SchemaExtender.php
  src/Utils/SchemaPrinter.php
  src/Utils/TypeInfo.php
  src/Utils/Utils.php
  src/Utils/Value.php
  src/Validator/Rules/KnownArgumentNames.php
  src/Validator/Rules/KnownArgumentNamesOnDirectives.php
  src/Validator/Rules/KnownDirectives.php
  src/Validator/Rules/NoFragmentCycles.php
  src/Validator/Rules/OverlappingFieldsCanBeMerged.php
  src/Validator/Rules/QueryComplexity.php
  src/Validator/Rules/ValuesOfCorrectType.php
  tests/Executor/SyncTest.php
  tests/Language/LexerTest.php
  tests/Type/ValidationTest.php
Labels: enhancement

#900 Clean up BreakingChangesFinder
  src/Utils/BreakingChangesFinder.php
Labels: enhancement

#901 Remove deprecations
  CHANGELOG.md
  src/Error/Error.php
  src/Executor/Values.php
  src/GraphQL.php
  src/Server/Helper.php
  src/Type/Schema.php
  src/Utils/AST.php
  src/Utils/BreakingChangesFinder.php
  src/Utils/TypeInfo.php
  src/Validator/DocumentValidator.php
  tests/Error/ErrorTest.php
  tests/Executor/ExecutorTest.php
  tests/Type/LazyTypeLoaderTest.php
  tests/Type/SchemaTest.php
  tests/Utils/IsValidLiteralValueTest.php
  tests/Validator/QuerySecurityTestCase.php
  tests/Validator/ValidatorTestCase.php
  tests/Validator/ValuesOfCorrectTypeTest.php
Labels: BC break
