Repository webonyx/graphql-php, pull requests merged in 2022-06, with the labels that each got.

#1167 Do not change HTTP status code in `StandardServer`
  CHANGELOG.md
  examples/01-blog/graphql.php
  examples/03-standard-server/graphql.php
  src/Server/Helper.php
  src/Server/StandardServer.php
Labels: enhancement, BC break

#1171 Avoid calling `FormattedError::addDebugEntries()` twice when using default error formatting
  CHANGELOG.md
  src/Error/FormattedError.php
Labels: bug

#1180 Ensure `InputObjectType::parseValue()` works with literals and extended schemas
  src/Utils/AST.php
  src/Utils/SchemaExtender.php
  tests/Type/InputObjectTypeTest.php
Labels: bug

#1185 Add `TypeInfo::getFieldDefStack()`
  CHANGELOG.md
  src/Utils/TypeInfo.php
Labels: enhancement

#1190 Simplify Schema::getType()
  src/Type/Schema.php
Labels: enhancement
