Repository webonyx/graphql-php, pull requests merged in 2023-02, with the labels that each got.

#1295 Fix `QueryPlan` when querying `__typename` on a `union` type
  CHANGELOG.md
  src/Type/Definition/QueryPlan.php
Labels: bug

#1297 Improve QueryPlan
  CHANGELOG.md
  src/Type/Definition/QueryPlan.php
  tests/Type/QueryPlanTest.php
Labels: bug, enhancement

#1292 Allow sorting more items in SchemaPrinter
  docs/class-reference.md
  src/Utils/SchemaPrinter.php
  tests/Utils/SchemaPrinterTest.php
Labels: enhancement

#1303 Fix ambiguity around when schema definition may be omitted
  src/Language/Printer.php
  src/Utils/SchemaPrinter.php
  tests/Language/SchemaPrinterTest.php
  tests/Utils/BuildSchemaTest.php
  tests/viralSchema.graphql
Labels: enhancement

#1313 Add method NodeList::reindex() for AST manipulation
  src/Language/AST/NodeList.php
  tests/Language/NodeListTest.php
Labels: enhancement
