Repository webonyx/graphql-php, pull requests merged in 2024-06, with the labels that each got.

#1548 Add unaliased path to resolve info
  docs/class-reference.md
  src/Error/Error.php
  src/Executor/ReferenceExecutor.php
  src/Type/Definition/ResolveInfo.php
  tests/Type/ResolveInfoTest.php
Labels: enhancement

#1577 fix(error): avoid phpunit crash by triggering side-effect via count on testcase
  composer.json
  src/Error/FormattedError.php
Labels: bug

#1287 Simplify blog example TypeRegistry
  examples/00-hello-world/README.md
  examples/00-hello-world/graphql.php
  examples/01-blog/Blog/Type/CommentType.php
  examples/01-blog/Blog/Type/Field/HtmlField.php
  examples/01-blog/Blog/Type/ImageType.php
  examples/01-blog/Blog/Type/NodeType.php
  examples/01-blog/Blog/Type/QueryType.php
  examples/01-blog/Blog/Type/SearchResultType.php
  examples/01-blog/Blog/Type/StoryType.php
  examples/01-blog/Blog/Type/UserType.php
  examples/01-blog/Blog/TypeRegistry.php
  examples/01-blog/Blog/Types.php
  examples/01-blog/README.md
  examples/01-blog/graphql.php
  examples/02-schema-definition-language/README.md
  examples/02-schema-definition-language/graphql.php
  examples/03-standard-server/README.md
  examples/03-standard-server/graphql.php
  examples/04-async-php/amphp/event-loop/graphql.php
  examples/04-async-php/amphp/http-server/graphql.php
  examples/04-async-php/reactphp/hello-world-http-server/graphql.php
  tests/Type/InputObjectTypeTest.php
Labels: docs

#1579 Ensure unaliasedPath does not grow for each list item
  CHANGELOG.md
  src/Executor/ReferenceExecutor.php
Labels: bug

#1581 Avoid infinite recursion in `QueryDepth` validator
  CHANGELOG.md
  src/Validator/Rules/QueryDepth.php
  tests/Validator/QueryDepthTest.php
Labels: bug
